study(title="Lejen", shorttitle="Lejen", overlay=true)

Ema8=ema(close, 8)
Ema21=ema(close, 21)
Ema55=ema(close, 55)

[macdLine, signalLine, histLine]=macd(close, 21, 34, 13)
rsi=rsi(close,13)
plot(Ema8, title="EMA 8", color=blue, style=line, linewidth=1)
plot(Ema21, title="EMA 21", color=red, style=line, linewidth=1)
plot(Ema55, title="EMA 55", color=lime, style = line, linewidth=1)

buy1=crossover(Ema8, Ema21) and close > Ema55
buy2=crossover(macdLine, signalLine) and Ema8 > Ema21 and close > Ema55 and rsi > 50

plotshape(buy1? buy1 : na, title="Buy Signal 1", style=shape.triangleup, location=location.belowbar, color=yellow, size=size.tiny)
plotshape(buy2? buy2 : na, title="Buy Signal 1", style=shape.triangleup, location=location.belowbar, color=lime, size=size.tiny)
